diff --git a/extensions/browser/extension_function_histogram_value.h b/extensions/browser/extension_function_histogram_value.h
index 6d9bd29ae220f..040d7493d5fd6 100644
--- a/extensions/browser/extension_function_histogram_value.h
+++ b/extensions/browser/extension_function_histogram_value.h
@@ -2011,6 +2011,30 @@ enum HistogramValue {
   DEVELOPERPRIVATE_SHOWSITESETTINGS = 1948,
   ACCESSIBILITY_PRIVATE_PROCESSPENDINGSPOKENFEEDBACKEVENT = 1949,
   ACCESSIBILITY_PRIVATE_ENABLESPOKENFEEDBACKMV3KEYHANDLING = 1950,
+  BROWSER_OS_GETACCESSIBILITYTREE = 1951,
+  BROWSER_OS_GETINTERACTIVESNAPSHOT = 1952,
+  BROWSER_OS_CLICK = 1953,
+  BROWSER_OS_INPUTTEXT = 1954,
+  BROWSER_OS_CLEAR = 1955,
+  BROWSER_OS_GETPAGELOADSTATUS = 1956,
+  BROWSER_OS_SCROLLUP = 1957,
+  BROWSER_OS_SCROLLDOWN = 1958,
+  BROWSER_OS_SCROLLTONODE = 1959,
+  BROWSER_OS_SENDKEYS = 1960,
+  BROWSER_OS_GETPAGESTRUCTURE = 1961,
+  BROWSER_OS_CAPTURESCREENSHOT = 1962,
+  BROWSER_OS_GETSNAPSHOT = 1963,
+  BROWSER_OS_GETPREF = 1964,
+  BROWSER_OS_SETPREF = 1965,
+  BROWSER_OS_GETALLPREFS = 1966,
+  BROWSER_OS_LOGMETRIC = 1967,
+  BROWSER_OS_GETVERSIONNUMBER = 1968,
+  BROWSER_OS_EXECUTEJAVASCRIPT = 1969,
+  BROWSER_OS_CLICKCOORDINATES = 1970,
+  BROWSER_OS_TYPEATCOORDINATES = 1971,
+  SIDEPANEL_BROWSEROSTOGGLE = 1972,
+  SIDEPANEL_BROWSEROSISOPEN = 1973,
+  BROWSER_OS_GETBROWSEROSVERSIONNUMBER = 1974,
   // Last entry: Add new entries above, then run:
   // tools/metrics/histograms/update_extension_histograms.py
   ENUM_BOUNDARY
